"""comment table

Revision ID: 01b8ef42b094
Revises: 8be9a595a173
Create Date: 2025-11-29 15:41:34.642417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b8ef42b094'
down_revision = '8be9a595a173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('image_phоto', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'image_phоto')
    # ### end Alembic commands ###
